/*


error.h


Error reporting hack


*/


#ifndef __ERRORHACK
#define __ERRORHACK

enum errorTypes {

   BLOCK_WRONGTYPE = 1,
   BLOCK_EMPTYWORD,
   BLOCK_WHITESPACE,
   BLOCK_EMPTYLINE,
   BLOCK_NEWLINE,   // 5
   BLOCK_NEGATIVEINDENT,
   BLOCK_BADLINESIZE,
   BLOCK_INDENTLARGERTHANLINESIZE,
   BLOCK_MAXWORDSREACHED,
   PAR_MAXBLOCKSREACHED,  // 10
   PAR_NOMEMORY,
   BEAUTIFY_NOMEMORY,
   SS_NOMEMORY,
   SS_POPWITHNULLSTRING,
   SS_POPPINGFROMANEMPTYSTACK, // 15
   SS_PUSHINGONADESTROYEDSTACK,
   SS_SEARCHINGONADESTROYEDSTACK,
   SS_MAXSTRINGSREACHED
};

int errorNumber(void);

int errorSetErrorNumber(int e);

#endif


